name: munchy
description: A new Flutter application.

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  modal_progress_hud: ^0.1.3
  firebase_core: ^0.5.0
  firebase_auth: ^0.18.0+1
  cloud_firestore: ^0.14.0+2
  cupertino_icons: ^0.1.3
  persistent_bottom_nav_bar: ^2.0.5
  sqflite: ^1.3.0
  path_provider: ^1.6.14
  flutter_bloc: ^6.0.5
  provider: ^4.0.5+1
  flutter_pagewise: ^1.2.3
  material_floating_search_bar: ^0.1.7
  bordered_text: ^1.0.0
  image_picker: ^0.6.7+11
  dropdownfield: ^1.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  assets:
    - assets/ingredients.txt
    - images/
  uses-material-design: true
  fonts:
    - family: Lobster
      fonts:
        - asset: fonts/Lobster-Regular.ttf
    - family: IndieFlower
      fonts:
        - asset: fonts/IndieFlower-Regular.ttf
    - family: Poppins
      fonts:
        - asset: fonts/Poppins-Regular.ttf
